### ISSUE TITLE
Windows Install Error

### ISSUE THREAD

**Issue by t0ta11ed** [CrowdStrike/ansible_collection_falcon#81] opened 2021-12-06 14:59 UTC
Hello, Falcon sensor install works just fine on Linux, but did require the ansible.windows collection along with it. 

Running the example playbook against a Windows Server 2019 machine returns the following error. 

TASK [crowdstrike.falcon.falcon_installation : ansible.builtin.include_tasks] ***17:22:28
included: /runner/requirements_collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/win_api.yml for Win2019Test

TASK [crowdstrike.falcon.falcon_installation : CrowdStrike Falcon | Authenticate to CrowdStrike API] ***17:22:28

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 50

fatal: [Win2019Test]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: The term 'Get-AnsibleWindowsWebRequestSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}

**Comment by redhatrises** [comment] 2021-12-06 22:10
Hello,

Thanks for opening this issue. What version of ansible are you running?

**Comment by t0ta11ed** [comment] 2021-12-06 22:45
ansible --version returns (core 2.11.2).

**Comment by redhatrises** [comment] 2021-12-08 20:53
Thanks for opening this.

This error does look like an ansible 2.9 to 2.11 error to me around using the FQCN where it is now recommended and didn't exist in 2.9

**Comment by t0ta11ed** [comment] 2021-12-14 13:01
Fortunately, I don't have that many Windows systems but it would be great if it worked for those too.

**Comment by ktinthecloud** [comment] 2021-12-29 23:57
Linux installations work fine, but getting the following error during Windows installations:

TASK [crowdstrike.falcon.falcon_installation : CrowdStrike Falcon | Download Falcon Sensor Installation Package] ***********************************************************************************************************
fatal: [hostname.MYDOMAIN.COM]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/win_api.yml': line 73, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package\n  ^ here\n"}

**Comment by redhatrises** [comment] 2022-01-14 15:47
The roles use the FQCN (Fully Qualified Collection Name) which isn't related to a system's FQDN at all. You can see where/how this issue arises in https://github.com/ansible-collections/ansible.windows/issues/138

**Comment by redhatrises** [comment] 2022-01-18 22:45
@t0ta11ed would you mind trying out https://cloud.redhat.com/ansible/automation-hub/repo/published/crowdstrike/falcon ?

**Comment by t0ta11ed** [comment] 2022-01-20 21:59
> @t0ta11ed would you mind trying out https://cloud.redhat.com/ansible/automation-hub/repo/published/crowdstrike/falcon ?

I updated to 3.2.3 without an issue, but still get the same error when deploying to a Windows 2019 Standard server.  The same playbook works fine against both CentOS and Ubuntu servers. 

```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 50
fatal: [AnsibleTest]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: The term 'Get-AnsibleWindowsWebRequestSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
```

**Comment by redhatrises** [comment] 2022-01-20 22:27
What version of the ansible windows collection are you using?

**Comment by t0ta11ed** [comment] 2022-01-21 16:34
> What version of the ansible windows collection are you using?

1.9.0 was installed when I upgraded the collection to 3.2.3

`# /root/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
ansible.windows    1.9.0  
azure.azcollection 1.8.0  
crowdstrike.falcon 3.2.3`

**Comment by carlosmmatos** [comment] 2022-01-27 18:45
@t0ta11ed I'm spinning something up to test this against ansible 2.9, but just to be sure I understand the issue, this only errors out on your Ansible Tower instance (which is using ansible  2.9.27 according to the docs) correct? Have you been able to test this outside of Ansible Tower?

**Comment by t0ta11ed** [comment] 2022-01-28 13:04
> 

Yes, running in Tower on Ansible 2.9. It works fine for Linux. I haven't tried it outside Tower, but will give it a whirl. Thanks!

**Comment by carlosmmatos** [comment] 2022-01-28 13:44
@t0ta11ed Thanks for confirming and my testing also did confirm that this issue is tied to Ansible 2.9. Since we only support Ansible 2.11+ for this collections, we will be closing this issue. Few things for you to consider or be aware:

- Even though we chose to support 2.11+, technically on Linux systems, 2.9 is still pretty backwards compatible to a certain point. This is why your Linux systems don't have issues running on Tower.
- If Ansible Tower is a product you are licensed for, then I would suggest considering upgrading to AAP (Ansible Automation Platform) 2.0+, as this is when they moved away from 2.9. 
- If the above is not possible, then consider using another system (not Tower) to manage the your Windows systems. This way you have control over the version of Ansible being used.

**Closed by carlosmmatos** 2022-01-28 13:44 UTC

**Comment by t0ta11ed** [comment] 2022-01-28 14:00
Sorry, I may have been mistaken. If I run ansible --version it's running 2.11; 

ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

If I go to Help > About in Tower,  I am running Ansible Automation Platform 4.0.0

**Comment by carlosmmatos** [comment] 2022-01-28 15:19
@t0ta11ed hmmmm... this is interesting then.. the symptoms you are seeing are as if the ansible system running the playbook from tower/aap is using ansible 2.9..

I would suggest the following:

1. You still haven't told us if you could run this playbook outside of AAP/Tower. If you can, then you have identified the issue to be with AAP/Tower.
2. If you have the same issue when running this outside your AAP/Tower instance, re-open this comment. Otherwise, if the issue is in AAP/Tower, then I would suggest reaching out to Red Hat for assistance.
