### ISSUE TITLE
Windows error with become when uninstalling

### ISSUE THREAD

**Issue by dmccue** [CrowdStrike/ansible_collection_falcon#20] opened 2021-01-31 22:10 UTC
Firstly, great collection this is absolutely the best way to deploy falcon (via ansible collection)

Having an issue with windows when using:
```
    - role: crowdstrike.falcon.falcon
      vars:
        falcon_uninstall: true
```

TASK [crowdstrike.falcon.falcon : CrowdStrike Falcon | Stopping Falcon Service] ***
Sunday 31 January 2021  22:04:21 +0000 (0:00:01.051)       0:03:37.052 ******** 
fatal: [i-********************]: FAILED! => {"msg": "The powershell shell family is incompatible with the sudo become plugin"}

I think a guard is needed to only use become when system is 'Linux':
`  when: ansible_system == 'Linux'`

There seems to be a number of glitches in the role, have you considered setting up molecule testing?
https://molecule.readthedocs.io/en/latest/

**Comment by shawndwells** [comment] 2021-02-04 18:04
Thanks for reporting this @dmccue! We'll start looking into this.

**Comment by redhatrises** [comment] 2021-02-04 23:50
@dmccue Windows isn't really support atm, so errors expected.

**Comment by redhatrises** [comment] 2021-03-04 23:42
@dmccue I am unable to reproduce this when attempting to run the playbook on a windows system. Looks like the `become_method` isn't setup correctly for windows hosts in either the `ansible.cfg` or the inventory.

**Comment by dmccue** [comment] 2021-03-04 23:48
Yes a conditional guard is needed so that it only runs on Linux i.e.

when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

**Comment by redhatrises** [comment] 2021-03-04 23:54
Looks like the wrong collection is being used as well. Please use the `crowdstrike.falcon.falcon_installation` role.

**Comment by redhatrises** [comment] 2021-03-10 23:55
This should be fixed in the latest release which should be able to run on Windows. Thanks for reporting and feel free to reopen if it isn't fixed.

**Closed by redhatrises** 2021-03-10 23:55 UTC
